name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow for professional_website
        run: |
        curl -XPOST -u "bitterdev:${PRIVATE_ACCESS_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/bitterdev/professional_website/dispatches --data '{"event_type": "build_application"}'
    
      - name: Trigger Build Workflow for professional_shop
        run: |
        curl -XPOST -u "bitterdev:${PRIVATE_ACCESS_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/bitterdev/professional_shop/dispatches --data '{"event_type": "build_application"}'
